stages:
  - test

Test_server:
  image: node:21-bookworm
  stage: test
  tags:
    - pihome
  script:
    - npm config set fetch-timeout 600000
    - cd mldonkey-next-backend
    - npm i --maxsockets 1
    - npm run build
    - npm run lint
    - cd ../mldonkey-next-frontend
    - npm i --maxsockets 1
    - npm run lint
    - npx ng build
