stages:
  - test

Test_server:
  image: node:20.5.0
  stage: test
  tags:
    - pihome
  script:
    - cd mldonkey-next-backend
    - npm i
    - npm run build
    - npm run lint
    - cd ../mldonkey-next-frontend
    - npm i
    - npx ng build
