stages:
  - test

Test_server:
  image: node:21-bookworm
  stage: test
  tags:
    - pihome
  script:
    - npm config set fetch-timeout 60000
    - npm config set registry http://registry.npmjs.org/
    - cd mldonkey-next-backend
    - npm i
    - npm run build
    - npm run lint
    - cd ../mldonkey-next-frontend
    - npm i
    - npm run lint
    - npx ng build
