variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - test_webapp
  - test_app

Test_webapp:
  image: node:22-bookworm
  stage: test_webapp
  artifacts:
    untracked: true
  tags:
    - pihome
  script:
    - npm config set fetch-timeout 600000
    - cd mldonkey-next-backend
    - npm i --maxsockets 1
    - npm run build
    - npm run lint
    - cd ../mldonkey-next-frontend
    - npm i --maxsockets 1
    - npm run lint
    - npx ng build --output-hashing none

Test_app:
  image:
    name: carlonluca/qt-dev:6.7.3
    entrypoint: [""]
  stage: test_app
  dependencies:
    - Test_webapp
  tags:
    - amd64
  script:
    - mkdir -p app/build
    - cd app/build
    - cmake ..
    - cmake --build .
